package com.sanskar.eventhive.ui.navigation

enum class Screen {
    INTRO,
    LOGIN,
    SIGNUP,
    VERIFY,
    COLLEGE_CODE_ENTRY,

    CREATE_CATEGORY_SCREEN,
    ALL_CATEGORY_SCREEN,
    SINGLE_CATEGORY_SCREEN,
    CATEGORY_SETTING_SCREEN,

    CREATE_EVENT_SCREEN,
    EVENT_DETAIL_SCREEN,
    EVENT_REGISTRATION_SCREEN,
    EVENT_SETTING_SCREEN,
    ALL_TEAMS_FOR_EVENT,
    TEAM_DETAIL_SCREEN,

    //bottom bar
    HOME,
    All_CLUBS_SCREEN,
    CLUB_DETAIL_SCREEN,
    CREATE_CLUB_SCREEN,
    EDIT_CLUB_SCREEN,
    CLUB_SETTING_SCREEN,
    MANAGE_CLUB_ROLES,
    CHATS,
    PROFILE,

    //User
    User_TICKET_SCREEN,
    User_EVENT_SCREEN,
    User_CLUB_SCREEN,
    EDIT_PROFILE_SCREEN,
    USER_TICKET_DETAIL_SCREEN,

    // Notifications
    NOTIFICATIONS,

    // Privacy Policy
    PRIVACY_POLICY_SCREEN,

    // Report Bug
    REPORT_BUG_SCREEN,
    // Notification
    NOTIFICATION_SCREEN,

    // Multi-college + admin
    CHAT_HOME,
    CHAT_ROOM,
    CHAT_ANON,
    COLLEGE_ADMIN_DASHBOARD,
    COLLEGE_ADMIN_ROLES,
    COLLEGE_ADMIN_ASSIGN_ROLE,
    COLLEGE_ADMIN_MEMBERS,
    COLLEGE_ADMIN_COLLEGE_CODE,
    COLLEGE_ADMIN_REPORTS,
    SUPER_ADMIN_COLLEGES,
    SUPER_ADMIN_ADD_COLLEGE,
    SUPER_ADMIN_COLLEGE_DETAIL,
    SUPER_ADMIN_ANALYTICS,
}
